[package]
name = "love"
version = "0.2.0"
authors = ["snsvrno <snsvrno@tuta.io>"]

exclude = [
    "/tests"
]

[dependencies]
regex = "1.1"
zip = "0.5"
failure = "0.1"

platform-lp = "0.2"
version-lp = "0.2"